apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  labels:
    app: httpd
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: httpd
    type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pv-claim1
  labels:
    app: httpd
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels: 
    app: httpd
spec:
  selector:
   matchLabels:
     app: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: "pawnikhanna/web_server:v1"
        name: "httpd"
        ports:
         - containerPort: 30007
           name: httpd
        volumeMounts:
        - name: httpd-vol
          mountPath: /var/www/html
      volumes:
      - name: httpd-vol
        persistentVolumeClaim:
          claimName: httpd-pv-claim
